### ISSUE TITLE
通过视频生成词库时卡死

### ISSUE THREAD

**Issue by yaojunqiang** [tangshimin/MuJing#13]
在mac book pro 上， 用mkv视频生成词库时卡死； 用字幕生成词库时也卡死

**Comment by tangshimin** [comment]
是最新版吗？

1. 先用命令行的方式启动：在访达 > 应用程序 > 幕境的图标上，按鼠标右键 > 选择显示包内容 > 进入 Contents > 进入 MacOS > 然后双击 幕境。
2. 然后按照这个[文档](https://github.com/tangshimin/MuJing/wiki/%E5%A6%82%E4%BD%95%E7%94%A8-MKV-%E8%A7%86%E9%A2%91%E7%94%9F%E6%88%90%E8%AF%8D%E5%BA%93)的步骤再试一次生成词库，如果再次卡死，就把命令行的信息贴出来。

**Comment by yaojunqiang** [comment]
<img width="903" alt="image" src="https://github.com/tangshimin/MuJing/assets/1227181/cf7fc821-294c-449a-8537-ae666a12ad18">

**Comment by tangshimin** [comment]
这个 bug 是最近两个版本引入的，我会尽快修复。

**Comment by tangshimin** [comment]
如果现在要使用生成词库功能，需要把版本退回到 v2.0.3

**Comment by tangshimin** [comment]
试试最新版，看还会不会卡死。

**Comment by hanhuoer** [comment]
> 试试最新版，看还会不会卡死。

今天下午我在用这个功能的时候也会卡死，不过更新到 2.0.6 就好了。

操作系统：windows10
软件版本：2.0.5

**Comment by yaojunqiang** [comment]
新版2.0.6 没有问题了。 MacBookPro    Intel  CPU

**Comment by tangshimin** [comment]
#
