### ISSUE TITLE
建议:关于词频:可否设置前*个与*个之间的词来筛选

### ISSUE THREAD

**Issue by xyh2132** [tangshimin/MuJing#19]
目前根据词频生成单词本,有很不好的体验,比如,只能选择生成前1000个.5000个等. 无法选择前1000个-3000个之间的词.
所以现在不论生成前1000个,前2000个词频.都包括最基本的on, off ,in 等词.浪费时间
如何把前500个,前1000个次去掉,才是生成单词本的重点

**Comment by tangshimin** [comment]
好建议，下一个版本就可以加。
你现在就想删掉简单单词的话，可以打开【词库】>【过滤词库】，然后把生成的词库拖进去。
![image](https://github.com/tangshimin/MuJing/assets/16540656/45260189-5c0c-4a1d-9732-75184dd33eb9)

**Comment by xyh2132** [comment]
可否删除我的issue
