### ISSUE TITLE
求支持一下linux系统

### ISSUE THREAD

**Issue by JinBiLianShao** [tangshimin/MuJing#2]

**Comment by tangshimin** [comment]
等我把『间隔重复』功能加了，就适配 Linux。

**Comment by JiangLin998** [comment]
> 等我把『间隔重复』功能加了，就适配 Linux。

但是现在已经过去很久了 还没有适配吗？

**Comment by tangshimin** [comment]
> > 等我把『间隔重复』功能加了，就适配 Linux。
> 
> 但是现在已经过去很久了 还没有适配吗？

开始适配了，最快下一个版本就会发布

**Comment by tangshimin** [comment]
最新版打包了一个deb安装包，下载地址：https://github.com/tangshimin/MuJing/releases
