### ISSUE TITLE
可否增加自定义输入单词的功能

### ISSUE THREAD

**Issue by xyh2132** [tangshimin/MuJing#22]
close this

**Comment by tangshimin** [comment]
没有看懂这个功能，你能再详细的描述一下吗？

**Comment by xyh2132** [comment]
就是要自由练习单词,比如根据youtube上的常用英语语句, 在听看的同时,对陌生的单词,可以打开这个软件,在自由输入界面,反复输入联系.
可以参考这个网站https://www.eletypes.com 点击底部咖啡图标,进入自由输入模式Free typing mode

**Comment by xyh2132** [comment]
好像是为伪需求,请删除吧
