### ISSUE TITLE
MAC  M2 mini下启动后直接退出无法使用

### ISSUE THREAD

**Issue by breterniu** [tangshimin/MuJing#24]
按照文档说明开放了权限，app启动后直接退出

**Comment by tangshimin** [comment]
VLC 视频播放器安装了吗？

**Comment by tangshimin** [comment]
要选择 macOS 版本的 VLC

![image](https://github.com/tangshimin/MuJing/assets/16540656/1f71be22-5948-4df5-a97b-def77c8d6ae4)

选 macOS (Apple Silicon) 不行，程序现在有一个 bug, 安装 macOS (Apple Silicon) 后，启动程序会闪退。

**Comment by breterniu** [comment]
重新安装vlc就正常了，thanks！

**Comment by tangshimin** [comment]
[v2.2.25](https://github.com/tangshimin/MuJing/releases/tag/v2.2.25) 的 macOS 安装包使用的是 GitHub Action 的 Apple Silicon M1 打包的， 安装 macOS (Apple Silicon）版的 VLC 应该可以正常启动了。
