### ISSUE TITLE
软件很好用，但Win11经常 报毒啊，用一会就不能用了，要重新安装，有人有这个问题吗？

### ISSUE THREAD

**Issue by xjtumedicine** [tangshimin/MuJing#26]

**Comment by xjtumedicine** [comment]
我装的是最新版本，win11自带的防火墙报毒。

另外，貌似视频弹幕的时候，如果查看翻译，偶尔会崩溃，但是不是很频繁。

**Comment by tangshimin** [comment]
以前也有一个用户有这种情况 [为什么会提示病毒](https://github.com/tangshimin/typing-learner/issues/81),可能是误报。
你可以把 MuJing 添加到排除项 https://answers.microsoft.com/zh-hans/windows/forum/all/windows-defender-%E8%AF%AF%E6%9D%80/7b7b7604-e8b3-46a1-8be6-a11fa01831b6

**Comment by tangshimin** [comment]
关于查看翻译导致崩溃，你是使用鼠标查看的还是快速定位查看的？

**Comment by xjtumedicine** [comment]
谢谢，我试一下哈。

我用的时候翻译崩溃，是快速定位导致的。
