### ISSUE TITLE
请求增加一个每次拼完单词，自动再把单词读一遍的功能

### ISSUE THREAD

**Issue by Kailasa** [tangshimin/MuJing#28]
感谢作者的开发，这个软件很棒！

我有一个小小的请求：我在学习单词的时候会把一个单词打10次左右，现在软件只有第一次打单词的时候会自动读出单词读音，后面都不会再自动读单词了，所以每次都需要按ctrl + j快捷键来让它再读一次，这样有些一些麻烦。能不能每次打单词都让它自动读一遍呀？这样有利于记住单词的读音，记单词能够记得更牢。或者能不能出一个选项：喜欢只读一遍的就选只读一遍，喜欢每次都读的，可以选择每次都读？

再次感谢作者！

**Comment by tangshimin** [comment]
这个建议不错，单词发音会在下一个版本做一些调整。

**Comment by Kailasa** [comment]
感谢感谢

**Comment by tangshimin** [comment]
这个功能最新版实现了，在“发音设置” 里选择“播放多次”，就可以每次拼写结束后再播放一次单词发音。
![image](https://github.com/tangshimin/MuJing/assets/16540656/3d98962e-7a8e-4311-88f8-4b9d56c676f3)
