### ISSUE TITLE
如果把 VLC 的版本换成苹果芯片可以正常启动吗？

### ISSUE THREAD

**Issue by tangshimin** [tangshimin/MuJing#33]
最新版更新了 VLCJ 的版本，好像可以支持苹果芯片了，我没有苹果芯片的mac，所以不能测试是否支持苹果芯片。
有没有使用苹果芯片的用户帮我测试一下，把 VLC 的版本改为苹果芯片的版本，然后启动幕境，看能否正常启动？

**Comment by TtlyLynzie** [comment]
无法正常启动，打不开

**Comment by TtlyLynzie** [comment]
要怎么测试？

**Comment by tangshimin** [comment]
> 无法正常启动，打不开

你是苹果芯片，然后下载的是苹果芯片版的 VLC 吗？
![image](https://github.com/tangshimin/MuJing/assets/16540656/c33808c3-6a31-471f-9087-9405c5c359a1)

相关 Issue：https://github.com/tangshimin/MuJing/issues/24

**Comment by TtlyLynzie** [comment]
> > 无法正常启动，打不开
> 
> 你是苹果芯片，然后下载的是苹果芯片版的 VLC 吗？ ![image](https://user-images.githubusercontent.com/16540656/282859290-c33808c3-6a31-471f-9087-9405c5c359a1.png)
> 
> 相关 Issue：#24

对

**Comment by tangshimin** [comment]
选择苹果芯片上面的那个版本，macOS 版的 VLC。
![251888044-1f71be22-5948-4df5-a97b-def77c8d6ae4](https://github.com/tangshimin/MuJing/assets/16540656/49fe71dd-4159-45c8-b4b8-877b2f87f9b5)

**Comment by tangshimin** [comment]
不能正常启动

**Comment by tangshimin** [comment]
[v2.2.25](https://github.com/tangshimin/MuJing/releases/tag/v2.2.25) 的 macOS 安装包使用的是 GitHub Action 的 Apple Silicon M1 打包的， 安装 macOS (Apple Silicon）版的 VLC 应该可以正常启动了。

**Comment by TtlyLynzie** [comment]
> [v2.2.25](https://github.com/tangshimin/MuJing/releases/tag/v2.2.25) 的 macOS 安装包使用的是 GitHub Action 的 Apple Silicon M1 打包的， 安装 macOS (Apple Silicon）版的 VLC 应该可以正常启动了。

还是打不开

**Comment by tangshimin** [comment]
调试一天，绕了一大圈，和 JDK 的芯片架构有关，我使用的构建脚本里使用的 JDK 是 Intel 架构的，换成 arm64 架构的 JDK 又有一个bug https://bugs.openjdk.org/browse/JDK-8330891 等7月16号发布了 21.0.4 再测试。

**Comment by tangshimin** [comment]
[v2.3.2-aarch64](https://github.com/tangshimin/MuJing/releases/download/untagged-1f26e8459e2b190c514d/MuJing-2.3.1-aarch64.dmg) 试一下这个版本呢，能不能正常使用?

**Comment by TtlyLynzie** [comment]
> [v2.3.2-aarch64](https://github.com/tangshimin/MuJing/releases/download/v2.3.2/MuJing-2.3.1-aarch64.dmg) 试一下这个版本呢，能不能正常使用?

可以打开了

**Comment by tangshimin** [comment]
> > [v2.3.2-aarch64](https://github.com/tangshimin/MuJing/releases/download/v2.3.2/MuJing-2.3.1-aarch64.dmg) 试一下这个版本呢，能不能正常使用?
> 
> 可以打开了

好的，谢谢
