### ISSUE TITLE
Mac m1 无法导入txt/pdf文件生成词库

### ISSUE THREAD

**Issue by kingsblue** [tangshimin/MuJing#4]
本机为Mac M1最新版本系统，在安装最新版本幕境，使用txt和pdf生成词库时，出现导入单词数为0的情况。经过本人测试，在win/mac m1系统安装旧版本幕境均可正常生成词库，不知道是不是新版本的bug，望确认，谢谢！

**Comment by tangshimin** [comment]
定位到bug了。

**Comment by tangshimin** [comment]
内置词典的地址错误，所有的生成词库功能都不可用。
