### ISSUE TITLE
[bug]-长视频字幕词库播放报错

### ISSUE THREAD

**Issue by NirvanaWong** [tangshimin/MuJing#44]
为了更好些的利用美剧全集帮助背单词，通常需要将美剧等台词词库连接到正在背的专业词库中，但一个一个链接实在太慢，而且不利于文件管理。此时就需要将剧集合并后整成字幕词库，例如，我就将全集老友记合并为了一个时长89小时的超大视频，PotPlayer等播放器均能够正常播放）。然而，目前在Mujing生成的字幕词库中，似乎原视频超过24小时会就会在点击播放原文时报错（"Text "80:52:52.000" could not be parsed Invalid value for Hour Of Day valid values 0-23: 80"。），导致播放器卡死。希望该问题能够得到解决，感谢开发者！#bug

**Comment by tangshimin** [comment]
修复了，如果顺利的话今天就会发布新版本

**Comment by tangshimin** [comment]
全集老友记合并后有多少个G？

**Comment by tangshimin** [comment]
其实可以不用合并视频的，如果视频是 MKV 格式的视频，可以选择多个视频一起生成一个词库，然后使用 菜单栏 > 词库 > 链接字幕词库  功能链接到专业词库。

**Comment by NirvanaWong** [comment]
开发者您好！老友记10季合在一起共145G，时长共89小时。文件是MKV的，理论上是可以全部导入MuJing生成字幕的，但实际操作发现，直接从大量mkv文件生成字幕十分容易卡死或无法识别（尽管我电脑13th i9-13900K + MSI GeForce RTX 4090，已经算家用顶配）。。同时，我发现通过字幕文件.srt+视频的方式，处理速度十分快，且从不报错或卡死。因此我现在的操作是：

1. 先用python将所有视频合并；
3. 然后提取字幕.srt；
4. 最后根据字幕+视频生成词库。

此方案除了合并环节需要一些时间之外，其他环节速度起飞，我十分推荐该方案！

**Comment by tangshimin** [comment]
mkv视频太多了确实很慢

**Comment by tangshimin** [comment]
这回应该可以了，下载地址：https://github.com/tangshimin/MuJing/releases

**Comment by NirvanaWong** [comment]
感谢开发者！长视频播放已经实现，经多次测试，没有报错。
