### ISSUE TITLE
自动分章节功能没了？

### ISSUE THREAD

**Issue by RainPPR** [tangshimin/MuJing#5]
人教版八年级下册，没有章节。
现在（v2.0.2）使用，一是学习不方便，二是听写复习（需要选择章节）{index: 0, size: 0}
记得以前可以自动分章节来着？

**Comment by tangshimin** [comment]
以前的版本，如果词库是空的，也会显示有一个章节20个单词。本来要把这个bug解决的，结果把 `size > 0` 写成了,`size < 0`，测试的时候也没有测试正常的词库，所以正常的词库就显示不出章节了。
