### ISSUE TITLE
在字幕浏览器中遇到这种情况应该怎么办

### ISSUE THREAD

**Issue by TroyMitchell911** [tangshimin/MuJing#52]
![image](https://github.com/tangshimin/MuJing/assets/133468432/2f093df0-453b-4656-a576-8ca4910f713c)

**Comment by tangshimin** [comment]
这个不是SRT格式的字幕。

**Comment by TroyMitchell911** [comment]
> 这个不是SRT格式的字幕。

ass转的srt

**Comment by TroyMitchell911** [comment]
可能转换过程中有些错误 我看了srt文件的内容 手动删除就好了
