### ISSUE TITLE
导入的pdf文件根据词频过滤后的单词，如何保存为每行一词的txt格式

### ISSUE THREAD

**Issue by xyh2132** [tangshimin/MuJing#55]
软件可以导入pdf根据词频过滤熟悉的单词后，会把过滤后的单词生成为json文件，请教如何把过滤后的单词列表导出为txt文件，仅有一行一个单词的那种txt

**Comment by tangshimin** [comment]
词库菜单栏 -> 编辑词库 -> 选择一个词库 -> 点击设置旁边的  导出 按钮 -> 然后把格式设置为   文本文件  -> 导出
如果要打印的话，我觉得导出 Excel 工作簿更合适。

**Comment by xyh2132** [comment]
thanks， 已解决，非常好的软件，请坚持
