### ISSUE TITLE
win11平台2.1.1版本之后MuJing.exe文件无法打开

### ISSUE THREAD

**Issue by Uranus-hanming** [tangshimin/MuJing#57]
我在win11平台上，下载安装应用程序后尝试打开MuJing.exe文件，在2.1.1版本及之前的所有版本都可以打开，在2.1.1版本之后就不行了。我注意到2.1.1版本及之前的所有版本都默认安装在C盘下的MuJing文件夹下，2.1.1版本之后默认安装在C盘下的名叫幕境的文件夹，开始以为是跟文件名是中文有关，尝试改为英文一样打不开，因此排除了这个猜想。

**Comment by tangshimin** [comment]
和英文名无关，我主要使用的操作系统也是 win11,安装后可以正常启动。
稍等几分钟，我马上上传一个带命令行的版本，安装后启动软件，看命令行有什么错误信息。

**Comment by Uranus-hanming** [comment]
好的，感谢回复



发自我的iPhone


------------------ 原始邮件 ------------------
From: tangshimin ***@***.***&gt;
发送时间: 05/26/2024, 23:44
To: tangshimin/MuJing ***@***.***&gt;
抄送: Uranus-hanming ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [tangshimin/MuJing] win11平台2.1.1版本之后MuJing.exe文件无法打开 (Issue #57)





 
和英文名无关，我主要使用的操作系统也是 win11,安装后可以正常启动。
 稍等几分钟，我马上上传一个带命令行的版本，安装后启动软件，看命令行有什么错误信息。

**Comment by tangshimin** [comment]
下载地址：https://github.com/tangshimin/MuJing/releases/download/v2.2.25/MuJing-2.2.25-command-line.msi

**Comment by Uranus-hanming** [comment]
终端没有内容打印，基本上双击MuJing.exe文件弹出终端2s后自动关闭了



发自我的iPhone


------------------ 原始邮件 ------------------
From: tangshimin ***@***.***&gt;
发送时间: 05/26/2024, 23:54
To: tangshimin/MuJing ***@***.***&gt;
抄送: Uranus-hanming ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [tangshimin/MuJing] win11平台2.1.1版本之后MuJing.exe文件无法打开 (Issue #57)





 
下载地址：https://github.com/tangshimin/MuJing/releases/download/v2.2.25/MuJing-2.2.25-command-line.msi

**Comment by tangshimin** [comment]
你是程序员吗？
我看你 Fork 了幕境，现在只能用 IDEA 调试了，你用 IDEA 把项目克隆到本地，然后双击运行 `runDistributable` 任务，看有没有什么错误信息。
![image](https://github.com/tangshimin/MuJing/assets/16540656/1cff7109-4069-4c71-869b-03477105f4f6)

**Comment by Uranus-hanming** [comment]
是的，我尝试一下



发自我的iPhone


------------------ 原始邮件 ------------------
From: tangshimin ***@***.***&gt;
发送时间: 05/27/2024, 00:52
To: tangshimin/MuJing ***@***.***&gt;
抄送: Uranus-hanming ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [tangshimin/MuJing] win11平台2.1.1版本之后MuJing.exe文件无法打开 (Issue #57)





 
你是程序员吗？
 我看你 Fork 了幕境，现在只能用 IDEA 调试了，你用 IDEA 把项目克隆到本地，然后双击运行 runDistributable 任务，看有没有什么错误信息。
 image.png (view on web)

**Comment by Uranus-hanming** [comment]
项目里找不到Tasks这个文件夹呢




秦时明月
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangshimin/MuJing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月27日(星期一) 凌晨0:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tangshimin/MuJing] win11平台2.1.1版本之后MuJing.exe文件无法打开 (Issue #57)





 
你是程序员吗？
 我看你 Fork 了幕境，现在只能用 IDEA 调试了，你用 IDEA 把项目克隆到本地，然后双击运行 runDistributable 任务，看有没有什么错误信息。
 image.png (view on web)

**Comment by tangshimin** [comment]
你用的是最新版IDEA 吗？
Tasks 在 Gradle 工具栏里面，如果没有看到 Gradle 可以在这里打开
![image](https://github.com/tangshimin/MuJing/assets/16540656/f23ac17c-5e09-4f1d-8b26-da7eb91e4c16)

**Comment by Uranus-hanming** [comment]
是什么IDEA，pycharm和vscode可以吗，还是java专门的IDEA，我对java不熟悉。




秦时明月
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangshimin/MuJing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月27日(星期一) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tangshimin/MuJing] win11平台2.1.1版本之后MuJing.exe文件无法打开 (Issue #57)





 
你用的是最新版IDEA 吗？
 Tasks 在 Gradle 工具栏里面，如果没有看到 Gradle 可以在这里打开
 image.png (view on web)

**Comment by tangshimin** [comment]
试试这个便携版 [幕境 v2.3.0](https://github.com/tangshimin/MuJing/releases/download/v2.3.0/MuJing-2.3.0-windows.zip) 解压缩后不要复制到C盘，复制到D盘再打开。

**Comment by tangshimin** [comment]
> 试试这个便携版 [幕境 v2.3.0](https://github.com/tangshimin/MuJing/releases/download/v2.3.0/MuJing-2.3.0-windows.zip) 解压缩后不要复制到C盘，复制到D盘再打开。

还真的可能是中文字符的问题,你把这个便携版解压之后的文件夹名称改成 mujing，然后把 幕境.exe 改成 mujing.exe 看能不能启动。

**Comment by Uranus-hanming** [comment]
可以打开了，非常感谢! 还有一点补充是幕境.cfg也要重命名为mujing.cfg




秦时明月
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangshimin/MuJing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月11日(星期二) 下午4:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tangshimin/MuJing] win11平台2.1.1版本之后MuJing.exe文件无法打开 (Issue #57)





  
试试这个便携版 幕境 v2.3.0 解压缩后不要复制到C盘，复制到D盘再打开。
  
还真的可能是中文字符的问题,你把这个便携版解压之后的文件夹名称改成 mujing，然后把 幕境.exe 改成 mujing.exe 看能不能启动。

**Comment by tangshimin** [comment]
你安装最新版了吗？
最新版安装后的安装路径变成 MuJing 了，没有安装的话可以帮我测试一下吗？

**Comment by Uranus-hanming** [comment]
已经成功安装最新版了，非常棒！




秦时明月
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangshimin/MuJing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月18日(星期三) 晚上8:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tangshimin/MuJing] win11平台2.1.1版本之后MuJing.exe文件无法打开 (Issue #57)






你安装最新版了吗？
最新版安装后的安装路径变成 MuJing 了，没有安装的话可以帮我测试一下吗？

**Comment by tangshimin** [comment]
好的，谢谢！
