### ISSUE TITLE
SRT字幕文件的序号不是以 1 开始并且不连续，幕境不能识别。

### ISSUE THREAD

**Issue by Helensberg** [tangshimin/MuJing#71]
选择srt字幕之后没法识别词频，怎么办。已经试了多个来源的字幕了
![截图_20240817134448](https://github.com/user-attachments/assets/74b30177-0316-40d9-96e6-cabda65636ad)

**Comment by tangshimin** [comment]
你用的是 macOS 吗？

**Comment by tangshimin** [comment]
如果是的话把软件升级到最新版

**Comment by Helensberg** [comment]
> 如果是的话把软件升级到最新版

不是macos，是windows的最新版。昨天你没回复的时候，我便携版和安装版都试过了，都是不行的

**Comment by tangshimin** [comment]
你试一下「使用文档生成词库功能」能不能生成词库？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月18日(周日) 中午11:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tangshimin/MuJing] 字幕识别不了 (Issue #71)




  
如果是的话把软件升级到最新版
  
不是macos，是windows的最新版。昨天你没回复的时候，我便携版和安装版都试过了，都是不行的

**Comment by tangshimin** [comment]
是一直都不能使用字幕生成词库？还是突然就不行的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月18日(周日) 中午11:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tangshimin/MuJing] 字幕识别不了 (Issue #71)




  
如果是的话把软件升级到最新版
  
不是macos，是windows的最新版。昨天你没回复的时候，我便携版和安装版都试过了，都是不行的

**Comment by Helensberg** [comment]
> 你试一下「使用文档生成词库功能」能不能生成词库？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月18日(周日) 中午11:16 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [tangshimin/MuJing] 字幕识别不了 (Issue #71) 如果是的话把软件升级到最新版 不是macos，是windows的最新版。昨天你没回复的时候，我便携版和安装版都试过了，都是不行的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

文档生成是可以的。字幕生成词库是一直不行。给您发送一些我刚才确认没法识别的字幕，供您参考。
[字幕.zip](https://github.com/user-attachments/files/16647117/default.zip)

**Comment by tangshimin** [comment]
字幕是正常的,可能是过滤区域的bug，生成词库的时候，左边过滤区一个都不勾选再试一下呢

**Comment by Helensberg** [comment]
> 字幕是正常的,可能是过滤区域的bug，生成词库的时候，左边过滤区一个都不勾选再试一下呢

![截图_20240818132048](https://github.com/user-attachments/assets/12f35ab1-a928-45bd-999e-ab49dbe51664)

都没勾选，还是不行呢

**Comment by tangshimin** [comment]
> > 字幕是正常的,可能是过滤区域的bug，生成词库的时候，左边过滤区一个都不勾选再试一下呢
> 
> ![截图_20240818132048](https://private-user-images.githubusercontent.com/35894018/358885911-12f35ab1-a928-45bd-999e-ab49dbe51664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTk5OTcsIm5iZiI6MTcyMzk1OTY5NywicGF0aCI6Ii8zNTg5NDAxOC8zNTg4ODU5MTEtMTJmMzVhYjEtYTkyOC00NWJkLTk5OWUtYWI0OWRiZTUxNjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA1NDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNDVmYjFiMjQ5YTdhNTVmNjljNTMyYzY3ZGM2ZTdhNzFmZGRjOGI5YzI4NGZhMTI1NTBlNjBiZjFiYWNmNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6CguZQKLGqITtaaOIS2aeOfaOFb9-6ZbiF5TU7wEK1k)
> 
> 都没勾选，还是不行呢

之前我只是打个看了一下字幕，觉得格式是正常的。
刚刚我仔细查看字幕文件，字幕的序号不正常。

**Comment by tangshimin** [comment]
最新版可以处理这种字幕了
