### ISSUE TITLE
pos字段的用途

### ISSUE THREAD

**Issue by strovsky** [tangshimin/MuJing#74]
我目前用2.5.0生成的结果文件pos字段都为空，是否是现在的正常情况？
另：
是否考虑增加一个字段保存单词所在的句子，导入一本书生成单词表的话，如果有这个字段会很有帮助；
谢谢！
我碰到的场景如下：
我的原始文件中有brownies这个词，记录的时候会将复数形式转换成单数形式browny（棕斑）保存【基于lemma.en】，实际上根据语境应该是brownie（巧克力蛋糕）的复数，所在句子为【Our big three products were boxed mixes for blueberry muffins, brownies, and Moist & Easy Snack Cake.】，有这个的化会帮助纠正；

**Comment by tangshimin** [comment]
是正常的，pos 字段在幕境里面没有实际使用，单词是从内置词典查询出来的，不确定未来会不会使用这个字段，就把它保留了。

保留单词所在的句子功能后续版本可能会添加。

**Comment by tangshimin** [comment]
我又查了一下，内置词典里面的所有单词的 pos 属性都是空的。
所以如果把单词对应的句子放到这个字段就不用处理向后兼容问题了。

**Comment by tangshimin** [comment]
![sentences](https://github.com/user-attachments/assets/468ede94-ccfe-4cfe-b2c6-19c4d926d1d0)
