### ISSUE TITLE
界面bug，试图删除某个单词时，‘X’号被遮挡。

### ISSUE THREAD

**Issue by benjstark** [tangshimin/MuJing#75]
![屏幕截图 2024-10-04 145749](https://github.com/user-attachments/assets/5a2a5922-ee62-499d-a29a-ae749b5bc4b2)
在导入词库时，企图删除一个熟悉的词汇，但是总是被遮挡。

期待您的回复，希望提的问题有用。

**Comment by tangshimin** [comment]
经复现，你反馈的 'X'被遮挡问题确实是一个bug，最后定位到问题是：最后一行的单词‘X'被遮挡，无法用鼠标删除。
我会尽快处理，感谢你的反馈。
