### ISSUE TITLE
bug：单词本最后一组单词个数不够20个时，不会弹出听写测试界面

### ISSUE THREAD

**Issue by benjstark** [tangshimin/MuJing#79]
举例来说，一个单词本有171个单词，20个单词一组，最后一组是从161到171，这一组单词不够20个，当我抄写到171个单词时，enter键后会直接跳转到第一个单词，不会弹出复习，听写等选项的界面。

希望我提的问题有用，感谢您花时间阅读我的问题。

**Comment by tangshimin** [comment]
windows 最新版我刚刚测试了，没有这个问题。
你用的是那个版本?

**Comment by benjstark** [comment]
可能是，我后面没有复现出来。
